### ISSUE TITLE
Not Working

### ISSUE THREAD

**Issue by Domingorp** [skagmo/esmart_mppt#1]
I’ve been looking for something like this, but it’s not working for me. I get an error about the global name “fields” not defined. I’m using python 3.5 and I’m fairly new at this language. Thanks for your efforts.

**Comment by skagmo** [comment]
Hi. This was a Python 2 project, but as I prefer Python 3 myself I've converted it now. Please try again with the latest commit and tell me how it works out.

**Comment by Domingorp** [comment]
Thanks for the quick response, It is not showing an error now, in fact, it is not showing anything. I believe it has to so with the serial port. I have one of those dongles and it works on my Windows computer using their software. I’ve used that dongle in the past with an EPEver MPPT controller until it burned out. Could it be that it needs to be set to "/dev/ttyUSB0" as the serial port?

Thanks,

Sent from Mail for Windows 10

**Comment by skagmo** [comment]
Hi. Not sure if I understand the issue. To make sure you are using the correct serial port, unplug and reinsert the dongle and run "dmesg". Check the last few lines for a new device on the form /dev/ttyUSB* or similar, and edit line 23 in esmart_test.py to match this device.

**Comment by jimbriam** [comment]
> Thanks for the quick response, It is not showing an error now, in fact, it is not showing anything. I believe it has to do with the serial port. I have one of those dongles and it works on my Windows computer using their software. I’ve used that dongle in the past with an EPEver MPPT controller until it burned out. Could it be that it needs to be set to "/dev/ttyUSB0" as the serial port? 

On Windows it is usually "COMx", x = 1
#e.open("COM1")

while on Linux it is usually "dev/ttyUSBx", x = 0
#e.open("/dev/ttyUSB0")
on linux the 'dmesg' command should make it clear what x should be

**Comment by Domingorp** [comment]
Done that already and still not working.  I purchased one of the dongles as recommended. I see the LEDs flashing, but nothing shows on the screen. I'll try again this weekend, in case I missed anything.

**Comment by skagmo** [comment]
Solved in issue #2
